"""update quest template schema

Revision ID: f44fe82f54f1
Revises: 44fe0b2ddfea
Create Date: 2026-07-07 18:06:49.391816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44fe82f54f1'
down_revision = '44fe0b2ddfea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titles_id', table_name='titles')
    op.drop_index('ix_titles_key', table_name='titles')
    op.drop_table('titles')
    op.drop_index('ix_character_profiles_id', table_name='character_profiles')
    op.drop_table('character_profiles')
    op.drop_index('ix_item_definitions_id', table_name='item_definitions')
    op.drop_index('ix_item_definitions_key', table_name='item_definitions')
    op.drop_table('item_definitions')
    op.drop_index('ix_boss_participations_boss_id', table_name='boss_participations')
    op.drop_index('ix_boss_participations_id', table_name='boss_participations')
    op.drop_index('ix_boss_participations_user_id', table_name='boss_participations')
    op.drop_table('boss_participations')
    op.drop_index('ix_bosses_cycle_end', table_name='bosses')
    op.drop_index('ix_bosses_cycle_start', table_name='bosses')
    op.drop_index('ix_bosses_id', table_name='bosses')
    op.drop_table('bosses')
    op.drop_index('ix_quest_logs_id', table_name='quest_logs')
    op.drop_index('ix_quest_logs_user_id', table_name='quest_logs')
    op.drop_table('quest_logs')
    op.drop_index('ix_user_titles_id', table_name='user_titles')
    op.drop_index('ix_user_titles_user_id', table_name='user_titles')
    op.drop_table('user_titles')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_firebase_uid', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_achievement_definitions_id', table_name='achievement_definitions')
    op.drop_index('ix_achievement_definitions_key', table_name='achievement_definitions')
    op.drop_table('achievement_definitions')
    op.drop_index('ix_user_inventory_items_id', table_name='user_inventory_items')
    op.drop_index('ix_user_inventory_items_user_id', table_name='user_inventory_items')
    op.drop_table('user_inventory_items')
    op.drop_index('ix_story_chapters_id', table_name='story_chapters')
    op.drop_index('ix_story_chapters_key', table_name='story_chapters')
    op.drop_table('story_chapters')
    op.drop_index('ix_quest_instances_assigned_date', table_name='quest_instances')
    op.drop_index('ix_quest_instances_id', table_name='quest_instances')
    op.drop_index('ix_quest_instances_user_id', table_name='quest_instances')
    op.drop_table('quest_instances')
    op.drop_index('ix_quest_templates_id', table_name='quest_templates')
    op.drop_index('ix_quest_templates_key', table_name='quest_templates')
    op.drop_table('quest_templates')
    op.drop_index('ix_story_progress_id', table_name='story_progress')
    op.drop_table('story_progress')
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_user_achievements_id', table_name='user_achievements')
    op.drop_index('ix_user_achievements_user_id', table_name='user_achievements')
    op.drop_table('user_achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_achievements',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('achievement_id', sa.CHAR(length=32), nullable=False),
    sa.Column('unlocked_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definitions.id'], name='fk_user_achievements_achievement_id_achievement_definitions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_achievements_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_achievements')
    )
    op.create_index('ix_user_achievements_user_id', 'user_achievements', ['user_id'], unique=False)
    op.create_index('ix_user_achievements_id', 'user_achievements', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('type', sa.VARCHAR(length=18), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_notifications_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_notifications')
    )
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.create_table('story_progress',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('current_chapter_index', sa.INTEGER(), nullable=False),
    sa.Column('unlocked_chapter_keys', sa.TEXT(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_story_progress_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_story_progress'),
    sa.UniqueConstraint('user_id', name='uq_story_progress_user_id')
    )
    op.create_index('ix_story_progress_id', 'story_progress', ['id'], unique=False)
    op.create_table('quest_templates',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=8), nullable=False),
    sa.Column('quest_type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=9), nullable=False),
    sa.Column('base_target', sa.FLOAT(), nullable=False),
    sa.Column('min_target', sa.FLOAT(), nullable=False),
    sa.Column('max_target', sa.FLOAT(), nullable=False),
    sa.Column('default_sets', sa.INTEGER(), nullable=True),
    sa.Column('default_reps_per_set', sa.INTEGER(), nullable=True),
    sa.Column('base_xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('primary_stat', sa.VARCHAR(length=32), nullable=False),
    sa.Column('secondary_stat', sa.VARCHAR(length=32), nullable=True),
    sa.Column('icon_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_quest_templates')
    )
    op.create_index('ix_quest_templates_key', 'quest_templates', ['key'], unique=1)
    op.create_index('ix_quest_templates_id', 'quest_templates', ['id'], unique=False)
    op.create_table('quest_instances',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('template_id', sa.CHAR(length=32), nullable=False),
    sa.Column('assigned_date', sa.DATE(), nullable=False),
    sa.Column('quest_type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=False),
    sa.Column('current_value', sa.FLOAT(), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('ai_rationale', sa.TEXT(), nullable=True),
    sa.Column('difficulty_snapshot', sa.FLOAT(), nullable=False),
    sa.Column('boss_participation_id', sa.CHAR(length=32), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['boss_participation_id'], ['boss_participations.id'], name='fk_quest_instances_boss_participation_id_boss_participations', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['quest_templates.id'], name='fk_quest_instances_template_id_quest_templates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_quest_instances_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_quest_instances')
    )
    op.create_index('ix_quest_instances_user_id', 'quest_instances', ['user_id'], unique=False)
    op.create_index('ix_quest_instances_id', 'quest_instances', ['id'], unique=False)
    op.create_index('ix_quest_instances_assigned_date', 'quest_instances', ['assigned_date'], unique=False)
    op.create_table('story_chapters',
    sa.Column('order_index', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('body_text', sa.TEXT(), nullable=False),
    sa.Column('unlock_level', sa.INTEGER(), nullable=True),
    sa.Column('unlock_streak_days', sa.INTEGER(), nullable=True),
    sa.Column('cover_art_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_story_chapters'),
    sa.UniqueConstraint('order_index', name='uq_story_chapters_order_index')
    )
    op.create_index('ix_story_chapters_key', 'story_chapters', ['key'], unique=1)
    op.create_index('ix_story_chapters_id', 'story_chapters', ['id'], unique=False)
    op.create_table('user_inventory_items',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('item_id', sa.CHAR(length=32), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('is_active_buff', sa.BOOLEAN(), nullable=False),
    sa.Column('buff_expires_at', sa.DATETIME(), nullable=True),
    sa.Column('acquired_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_definitions.id'], name='fk_user_inventory_items_item_id_item_definitions'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_inventory_items_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_inventory_items')
    )
    op.create_index('ix_user_inventory_items_user_id', 'user_inventory_items', ['user_id'], unique=False)
    op.create_index('ix_user_inventory_items_id', 'user_inventory_items', ['id'], unique=False)
    op.create_table('achievement_definitions',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('icon_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('xp_reward', sa.INTEGER(), nullable=False),
    sa.Column('is_hidden', sa.BOOLEAN(), nullable=False),
    sa.Column('unlock_condition_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_achievement_definitions')
    )
    op.create_index('ix_achievement_definitions_key', 'achievement_definitions', ['key'], unique=1)
    op.create_index('ix_achievement_definitions_id', 'achievement_definitions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('firebase_uid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_onboarded', sa.BOOLEAN(), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=64), nullable=False),
    sa.Column('primary_track', sa.VARCHAR(length=32), nullable=False),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_firebase_uid', 'users', ['firebase_uid'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('user_titles',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('title_id', sa.CHAR(length=32), nullable=False),
    sa.Column('unlocked_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], name='fk_user_titles_title_id_titles'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_titles_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_titles')
    )
    op.create_index('ix_user_titles_user_id', 'user_titles', ['user_id'], unique=False)
    op.create_index('ix_user_titles_id', 'user_titles', ['id'], unique=False)
    op.create_table('quest_logs',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('quest_instance_id', sa.CHAR(length=32), nullable=False),
    sa.Column('delta_value', sa.FLOAT(), nullable=False),
    sa.Column('resulting_value', sa.FLOAT(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=256), nullable=True),
    sa.Column('logged_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['quest_instance_id'], ['quest_instances.id'], name='fk_quest_logs_quest_instance_id_quest_instances', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_quest_logs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_quest_logs')
    )
    op.create_index('ix_quest_logs_user_id', 'quest_logs', ['user_id'], unique=False)
    op.create_index('ix_quest_logs_id', 'quest_logs', ['id'], unique=False)
    op.create_table('bosses',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('archetype', sa.VARCHAR(length=15), nullable=False),
    sa.Column('cycle', sa.VARCHAR(length=7), nullable=False),
    sa.Column('lore_text', sa.TEXT(), nullable=False),
    sa.Column('icon_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('cycle_start', sa.DATE(), nullable=False),
    sa.Column('cycle_end', sa.DATE(), nullable=False),
    sa.Column('max_hp', sa.FLOAT(), nullable=False),
    sa.Column('current_hp', sa.FLOAT(), nullable=False),
    sa.Column('is_defeated', sa.BOOLEAN(), nullable=False),
    sa.Column('defeated_at', sa.DATETIME(), nullable=True),
    sa.Column('reward_xp', sa.INTEGER(), nullable=False),
    sa.Column('reward_item_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_bosses')
    )
    op.create_index('ix_bosses_id', 'bosses', ['id'], unique=False)
    op.create_index('ix_bosses_cycle_start', 'bosses', ['cycle_start'], unique=False)
    op.create_index('ix_bosses_cycle_end', 'bosses', ['cycle_end'], unique=False)
    op.create_table('boss_participations',
    sa.Column('boss_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('damage_dealt', sa.FLOAT(), nullable=False),
    sa.Column('quests_contributed', sa.INTEGER(), nullable=False),
    sa.Column('joined_at', sa.DATETIME(), nullable=False),
    sa.Column('reward_claimed', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['bosses.id'], name='fk_boss_participations_boss_id_bosses', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_boss_participations_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_boss_participations')
    )
    op.create_index('ix_boss_participations_user_id', 'boss_participations', ['user_id'], unique=False)
    op.create_index('ix_boss_participations_id', 'boss_participations', ['id'], unique=False)
    op.create_index('ix_boss_participations_boss_id', 'boss_participations', ['boss_id'], unique=False)
    op.create_table('item_definitions',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('rarity', sa.VARCHAR(length=9), nullable=False),
    sa.Column('effect_type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('effect_value', sa.FLOAT(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('icon_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('is_stackable', sa.BOOLEAN(), nullable=False),
    sa.Column('is_tradeable', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_item_definitions')
    )
    op.create_index('ix_item_definitions_key', 'item_definitions', ['key'], unique=1)
    op.create_index('ix_item_definitions_id', 'item_definitions', ['id'], unique=False)
    op.create_table('character_profiles',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('current_xp', sa.INTEGER(), nullable=False),
    sa.Column('total_xp_earned', sa.INTEGER(), nullable=False),
    sa.Column('knowledge', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('stamina', sa.INTEGER(), nullable=False),
    sa.Column('recovery', sa.INTEGER(), nullable=False),
    sa.Column('focus', sa.INTEGER(), nullable=False),
    sa.Column('discipline', sa.INTEGER(), nullable=False),
    sa.Column('consistency', sa.INTEGER(), nullable=False),
    sa.Column('agility', sa.INTEGER(), nullable=False),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.Column('potential', sa.INTEGER(), nullable=False),
    sa.Column('luck', sa.INTEGER(), nullable=False),
    sa.Column('mental_fortitude', sa.INTEGER(), nullable=False),
    sa.Column('current_streak_days', sa.INTEGER(), nullable=False),
    sa.Column('longest_streak_days', sa.INTEGER(), nullable=False),
    sa.Column('last_quest_completed_date', sa.DATE(), nullable=True),
    sa.Column('active_title_id', sa.CHAR(length=32), nullable=True),
    sa.Column('difficulty_multiplier', sa.FLOAT(), nullable=False),
    sa.Column('burnout_risk_score', sa.FLOAT(), nullable=False),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['active_title_id'], ['titles.id'], name='fk_character_profiles_active_title_id_titles', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_character_profiles_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_character_profiles'),
    sa.UniqueConstraint('user_id', name='uq_character_profiles_user_id')
    )
    op.create_index('ix_character_profiles_id', 'character_profiles', ['id'], unique=False)
    op.create_table('titles',
    sa.Column('key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('display_text', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('required_level', sa.INTEGER(), nullable=True),
    sa.Column('required_achievement_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_titles')
    )
    op.create_index('ix_titles_key', 'titles', ['key'], unique=1)
    op.create_index('ix_titles_id', 'titles', ['id'], unique=False)
    # ### end Alembic commands ###
